CREATE TABLE IF NOT EXISTS planets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50),
  diameter DOUBLE,
  distance_from_sun DOUBLE,
  length_of_day DOUBLE,
  length_of_year DOUBLE,
  fun_facts JSON,
  image_url VARCHAR(255)
);

INSERT INTO planets (name, diameter, distance_from_sun, length_of_day, length_of_year, fun_facts, image_url) VALUES
('Sun', 1392700, 0, 0, 0, JSON_ARRAY('The Sun contains 99.86% of the mass in the Solar System', 'It takes about 8 minutes and 20 seconds for light from the Sun to reach Earth', 'The Sun''s atmosphere extends millions of kilometers into space and is visible during total solar eclipses', 'Every second, the Sun converts about 4 million tons of matter into energy', 'The temperature at the Sun''s core is around 15 million degrees Celsius (27 million degrees Fahrenheit)'), 'https://images-assets.nasa.gov/image/PIA03149/PIA03149~orig.jpg'),
('Mercury', 4880, 57900000, 1407.6, 88, JSON_ARRAY('Mercury is the smallest planet in the Solar System and is slightly larger than Earth''s Moon', 'It has no atmosphere to speak of, which means there is no weather or wind', 'Mercury has a very large iron core, which makes up about 75% of its diameter', 'A day on Mercury lasts approximately 59 Earth days', 'Despite being closest to the Sun, ice exists in the permanently shadowed craters on its poles'), 'https://images-assets.nasa.gov/image/PIA11245/PIA11245~orig.jpg'),
('Venus', 12104, 108200000, 5832.5, 224.7, JSON_ARRAY('Venus is the hottest planet in the Solar System, with surface temperatures hot enough to melt lead', 'Its day is longer than its year, taking 243 Earth days to rotate once, but only 225 to orbit the Sun', 'Venus rotates in the opposite direction to most planets, meaning the Sun rises in the west and sets in the east', 'It has over 1,600 major volcanoes, but none are known to be erupting', 'Venus'' thick atmosphere reflects sunlight very efficiently, making it the brightest planet as seen from Earth'), 'https://science.nasa.gov/wp-content/uploads/2023/05/venus-single.png?w=1024&format=webp'),
('Earth', 12742, 149600000, 24, 365.25, JSON_ARRAY('Earth is the only planet not named after a mythological god or goddess', 'It is the densest planet in the Solar System', 'About 71% of Earth’s surface is covered in water', 'Earth''s atmosphere is 78% nitrogen, 21% oxygen, with traces of argon, carbon dioxide, and water', 'Our planet is slowly drifting away from the Sun at a rate of about 1.5 cm per year'), 'https://images-assets.nasa.gov/image/PIA18033/PIA18033~orig.jpg'),
('Moon', 3475, 384400, 708.7, 27.3, JSON_ARRAY('The Moon is moving approximately 3.8 cm away from our planet every year', 'There are more than 300,000 craters wider than 1 km on the Moon’s near side alone', 'The Moon''s gravitational influence causes ocean tides on Earth', 'The same side of the Moon always faces Earth due to synchronous rotation', 'Lunar soil smells like spent gunpowder, according to Apollo astronauts'), 'https://images-assets.nasa.gov/image/as10-27-3956/as10-27-3956~orig.jpg'),
('Mars', 6779, 227900000, 24.6, 687, JSON_ARRAY('Mars is home to Olympus Mons, the tallest volcano and second-highest known mountain within the Solar System', 'It has the largest dust storms in the solar system, sometimes covering the entire planet', 'Pieces of Mars have fallen to Earth as meteorites', 'Mars has two moons, Phobos and Deimos, which are thought to be captured asteroids', 'Liquid water cannot exist on its surface today, but evidence suggests it may have flowed in the past'), 'https://images-assets.nasa.gov/image/PIA04272/PIA04272~orig.jpg'),
('Jupiter', 139822, 778600000, 9.9, 4331, JSON_ARRAY('Jupiter is the largest planet in our solar system, more than twice as massive as all the other planets combined', 'The Great Red Spot is a huge storm on Jupiter that has raged for at least 350 years', 'Jupiter has 79 moons, the largest of which are Ganymede, Callisto, Io, and Europa', 'It has the strongest magnetic field of any planet, roughly 20,000 times stronger than Earth’s', 'Jupiter''s famous bands are created by differences in thickness and height of ammonia ice clouds'), 'https://images-assets.nasa.gov/image/PIA22946/PIA22946~orig.jpg'),
('Saturn', 116460, 1433500000, 10.7, 10747, JSON_ARRAY('Saturn is best known for its prominent ring system, which is made mostly of ice particles and rocky debris', 'It has 82 moons, with Titan being larger than the planet Mercury', 'Saturn is the least dense planet in the Solar System; it would float if placed in a large enough body of water', 'Its interior is hot: Saturn radiates more than twice as much energy as it receives from the Sun', 'The length of a day on Saturn was a mystery until the Cassini spacecraft measured its rotation rate'), 'https://images-assets.nasa.gov/image/PIA04913/PIA04913~orig.jpg'),
('Uranus', 50724, 2872500000, 17.2, 30589, JSON_ARRAY('Uranus rotates on its side, with an axial tilt of 98 degrees, possibly due to a collision with an Earth-sized object long ago', 'It was the first planet discovered with a telescope, identified by William Herschel in 1781', 'Uranus has a faint ring system and 27 known moons', 'Its atmosphere is mostly hydrogen and helium, with a higher presence of "ices" such as water, ammonia, and methane compared to Jupiter and Saturn', 'Uranus takes about 84 Earth years to complete one orbit around the Sun'), 'https://images-assets.nasa.gov/image/PIA18182/PIA18182~orig.jpg'),
('Neptune', 49244, 4495100000, 16.1, 59800, JSON_ARRAY('Neptune was the first planet located through mathematical predictions rather than through regular observation', 'It has the strongest winds in the Solar System, reaching speeds of up to 2,100 kilometers per hour', 'Neptune''s blue color is due to the absorption of red light by methane in the atmosphere', 'It has 14 known moons, with Triton being the largest, which orbits Neptune in a direction opposite to the planet''s rotation', 'Neptune''s orbit is not completely circular, causing significant variations in its distance from the Sun'), 'https://images-assets.nasa.gov/image/PIA00046/PIA00046~orig.jpg'),
('Pluto', 2376, 5906380000, 153.3, 90560, JSON_ARRAY('Pluto was reclassified from a planet to a dwarf planet in 2006 by the International Astronomical Union', 'It has five known moons with Charon being the largest. Charon is so large that Pluto and Charon orbit each other like a double planet system', 'Pluto has a thin atmosphere that expands when it comes closer to the Sun and collapses as it moves further away', 'Its surface is composed of a mixture of frozen nitrogen, methane, and carbon monoxide', 'Pluto takes 248 Earth years to complete one orbit around the Sun'), 'https://images-assets.nasa.gov/image/PIA20291/PIA20291~orig.jpg');

SELECT * FROM planets;